# Generated by Django 4.0.2 on 2022-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('emp_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
